Repository AY2122S1-CS2103T-W10-2/tp, pull requests merged in 2021-11, with the labels that each got.

#225 Undo and redo command now works with list absent
  src/main/java/seedu/teachbook/logic/commands/ListCommand.java
  src/main/java/seedu/teachbook/logic/commands/RedoCommand.java
  src/main/java/seedu/teachbook/logic/commands/UndoCommand.java
  src/main/java/seedu/teachbook/model/ModelManager.java
  src/main/java/seedu/teachbook/model/TeachBook.java
  src/main/java/seedu/teachbook/model/VersionedTeachBook.java
Labels: type.Bug, priority.Medium

#230 Find command now works with list absent
  src/main/java/seedu/teachbook/logic/commands/FindCommand.java
Labels: type.Bug

#237 Reorder UG such that features now have sub-headers
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#238 Fix misdocumentation for find command spotted in PE-Dry Run
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#239 Add missing documentation in Remark and Grade commands in User Guide
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#235 Fix command spamming issue & code quality improvements
  src/main/java/seedu/teachbook/commons/util/ExcelUtil.java
  src/main/java/seedu/teachbook/logic/commands/PrintCommand.java
  src/main/java/seedu/teachbook/logic/parser/TeachBookParser.java
  src/main/java/seedu/teachbook/model/ModelManager.java
  src/main/java/seedu/teachbook/model/TeachbookDataState.java
  src/main/java/seedu/teachbook/model/TeachbookDisplayState.java
  src/main/java/seedu/teachbook/model/VersionedTeachBook.java
  src/main/java/seedu/teachbook/model/classobject/Class.java
  src/main/java/seedu/teachbook/model/student/Student.java
  src/main/java/seedu/teachbook/model/student/UniqueStudentList.java
Labels: type.Bug, priority.Medium

#240 Address issue on class name select issue in the class features and FAQ
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#224 UG: Add lag issue in faq
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#241 UG: TeachBook user guide now contains appropriate screenshots
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addClass.png
  docs/images/addStudent.png
  docs/images/deleteClass.png
  docs/images/deleteStudent.png
  docs/images/editClass.png
  docs/images/editStudent.png
  docs/images/excel.png
  docs/images/findStudent.png
  docs/images/gradeAll.png
  docs/images/listAll.png
  docs/images/markAttendance.png
  docs/images/remark.png
  docs/images/select_example.png
  docs/images/setGrade.png
  docs/images/unmark.png
Labels: type.Documentation, priority.Medium, type.Chore

#242 Solve some issues
  docs/UserGuide.md
  src/main/java/seedu/teachbook/commons/core/index/GeneralIndex.java
  src/main/java/seedu/teachbook/logic/commands/AddClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/AddCommand.java
  src/main/java/seedu/teachbook/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/DeleteCommand.java
  src/main/java/seedu/teachbook/logic/commands/EditClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/EditCommand.java
  src/main/java/seedu/teachbook/logic/commands/FindCommand.java
  src/main/java/seedu/teachbook/logic/commands/GradeCommand.java
  src/main/java/seedu/teachbook/logic/commands/ListCommand.java
  src/main/java/seedu/teachbook/logic/commands/MarkCommand.java
  src/main/java/seedu/teachbook/logic/commands/PrintCommand.java
  src/main/java/seedu/teachbook/logic/commands/ResetGradeCommand.java
  src/main/java/seedu/teachbook/logic/commands/SelectClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/SetGradeCommand.java
  src/main/java/seedu/teachbook/logic/commands/SortCommand.java
  src/main/java/seedu/teachbook/logic/commands/UnmarkCommand.java
  src/main/java/seedu/teachbook/model/Model.java
  src/main/java/seedu/teachbook/model/ModelManager.java
  src/test/java/seedu/teachbook/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.High

#243 Change GUI image in the UG
  docs/images/GUI.png
Labels: type.Documentation, priority.Low

#244 Delete and re-added the GUI image on UG because changes not being reflected
  docs/images/GUI.png
Labels: type.Documentation, priority.Low

#247 Update print command error message
  src/main/java/seedu/teachbook/commons/util/ExcelUtil.java
  src/main/java/seedu/teachbook/logic/commands/PrintCommand.java
Labels: type.Enhancement, priority.Medium

#251 Change error message for negative and huge indices
  src/main/java/seedu/teachbook/commons/util/StringUtil.java
  src/main/java/seedu/teachbook/logic/parser/ParserUtil.java
  src/test/java/seedu/teachbook/commons/util/StringUtilTest.java
  src/test/java/seedu/teachbook/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/teachbook/logic/parser/ParserUtilTest.java
Labels: type.Enhancement, priority.Medium

#252 Update tests and fix a bug
  src/main/java/seedu/teachbook/logic/parser/RemarkCommandParser.java
  src/test/java/seedu/teachbook/commons/util/StringUtilTest.java
  src/test/java/seedu/teachbook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/teachbook/testutil/TypicalIndexes.java
Labels: type.Bug, priority.High

#253 Let user know that adding student with exact same name is not possible
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#254 Update Wilfred PPP
  docs/team/wilfredwongkc.md
Labels: type.Documentation, priority.Low

#255 Draft PPP
  docs/team/fans2619.md
Labels: type.Documentation, priority.High

#258 DG updates
  docs/DeveloperGuide.md
  docs/team/yulonglim.md
Labels: type.Documentation, priority.Medium, type.Chore

#259 DG: update Design > Architecture, Common classes
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ComponentManagers.png
Labels: type.Documentation

#260 Added TestCases for JsonAdaptedClass
  src/main/java/seedu/teachbook/model/student/Student.java
  src/test/java/seedu/teachbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/teachbook/storage/JsonAdaptedClassTest.java
  src/test/java/seedu/teachbook/testutil/ClassBuilder.java
  src/test/java/seedu/teachbook/testutil/TypicalClasses.java
  src/test/java/seedu/teachbook/testutil/TypicalStudents.java
Labels: priority.Medium, type.Chore

#263 Improve test code
  src/test/data/JsonSerializableTeachBookTest/duplicateClassTeachBook.json
  src/test/data/JsonSerializableTeachBookTest/duplicateStudentTeachBook.json
  src/test/data/JsonSerializableTeachBookTest/invalidGradeTeachBook.json
  src/test/data/JsonSerializableTeachBookTest/invalidStudentTeachBook.json
  src/test/data/JsonSerializableTeachBookTest/typicalStudentsTeachBook.json
  src/test/java/seedu/teachbook/testutil/TypicalStudents.java
Labels: priority.Low, type.Chore

#264 Wrote test code for excel util
  src/main/java/seedu/teachbook/logic/commands/PrintCommand.java
  src/test/java/seedu/teachbook/commons/util/ExcelUtilTest.java
Labels: priority.Low, type.Chore

#266 Expalin in UG that the mark/unmark command will un-filter a filtered list
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#268 Update PPP
  docs/team/xyliew25.md
Labels: type.Documentation, priority.High

#270 Update design part for UI component in DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Low

#271 Update wilfred ppp
  docs/team/wilfredwongkc.md
Labels: type.Documentation, priority.Low

#272 Add test classes for UI part and trial test for classCard
  build.gradle
  src/test/java/seedu/teachbook/ui/ClassCardTest.java
  src/test/java/seedu/teachbook/ui/ClassListPanelTest.java
  src/test/java/seedu/teachbook/ui/CommandBoxTest.java
  src/test/java/seedu/teachbook/ui/HelpWindowTest.java
  src/test/java/seedu/teachbook/ui/MainWindowTest.java
  src/test/java/seedu/teachbook/ui/ResultDisplayTest.java
  src/test/java/seedu/teachbook/ui/StatusBarFooterTest.java
  src/test/java/seedu/teachbook/ui/StudentCardTest.java
  src/test/java/seedu/teachbook/ui/StudentListPanelTest.java
  src/test/java/seedu/teachbook/ui/UiManagerTest.java
Labels: priority.Low

#273 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ListAbsentSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/ListAbsentSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
Labels: type.Documentation, priority.High

#274 Add JavaDocs
  src/main/java/seedu/teachbook/logic/commands/AddCommand.java
  src/main/java/seedu/teachbook/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/MarkCommand.java
  src/main/java/seedu/teachbook/logic/commands/UnmarkCommand.java
  src/main/java/seedu/teachbook/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/DeleteClassCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/FindCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/MarkCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/ParserUtil.java
  src/main/java/seedu/teachbook/logic/parser/Prefix.java
  src/main/java/seedu/teachbook/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/teachbook/model/student/Address.java
  src/main/java/seedu/teachbook/model/student/Attendance.java
  src/main/java/seedu/teachbook/model/student/Email.java
  src/main/java/seedu/teachbook/model/student/Name.java
  src/main/java/seedu/teachbook/model/student/Phone.java
  src/main/java/seedu/teachbook/model/student/Student.java
  src/test/java/seedu/teachbook/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/teachbook/logic/commands/AddCommandTest.java
Labels: type.Documentation

#275 Updated DG and PPP
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/UndoSequenceDiagram.png
  docs/team/yulonglim.md
Labels: type.Documentation, priority.Medium

#276 Write first part of Javadoc
  src/main/java/seedu/teachbook/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/DeleteCommand.java
  src/main/java/seedu/teachbook/logic/commands/ListCommand.java
  src/main/java/seedu/teachbook/logic/commands/RemarkCommand.java
  src/main/java/seedu/teachbook/logic/commands/SelectClassCommand.java
  src/main/java/seedu/teachbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/GradeCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/ListCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/ParserUtil.java
  src/main/java/seedu/teachbook/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/SelectClassCommandParser.java
Labels: priority.Medium, type.Chore

#277 Update JavaDocs
  src/main/java/seedu/teachbook/logic/commands/AddCommand.java
  src/main/java/seedu/teachbook/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/MarkCommand.java
  src/main/java/seedu/teachbook/logic/commands/UnmarkCommand.java
  src/main/java/seedu/teachbook/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/DeleteClassCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/FindCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/MarkCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/ParserUtil.java
  src/main/java/seedu/teachbook/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/teachbook/model/student/Address.java
  src/main/java/seedu/teachbook/model/student/Attendance.java
  src/main/java/seedu/teachbook/model/student/Email.java
  src/main/java/seedu/teachbook/model/student/Name.java
  src/main/java/seedu/teachbook/model/student/Phone.java
  src/main/java/seedu/teachbook/model/student/Student.java
Labels: type.Documentation

#279 Write second part of Javadoc
  src/main/java/seedu/teachbook/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/ListCommand.java
  src/main/java/seedu/teachbook/logic/commands/SelectClassCommand.java
  src/main/java/seedu/teachbook/model/classobject/ClassName.java
  src/main/java/seedu/teachbook/model/classobject/ClassNameDescriptor.java
  src/main/java/seedu/teachbook/model/gradeobject/GradingSystem.java
  src/main/java/seedu/teachbook/model/student/Remark.java
  src/main/java/seedu/teachbook/model/student/StudentIsAbsentPredicate.java
Labels: priority.Medium, type.Chore

#280 Add Javadoc and improve code quality
  config/checkstyle/suppressions.xml
  docs/SettingUp.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/teachbook/MainApp.java
  src/main/java/seedu/teachbook/commons/core/index/DefaultIndices.java
  src/main/java/seedu/teachbook/commons/core/index/GeneralIndex.java
  src/main/java/seedu/teachbook/commons/core/index/IndexComparator.java
  src/main/java/seedu/teachbook/commons/util/StringUtil.java
  src/main/java/seedu/teachbook/model/ReadOnlyTeachBook.java
  src/main/java/seedu/teachbook/model/UserPrefs.java
  src/main/java/seedu/teachbook/model/classobject/exceptions/DuplicateClassException.java
  src/main/java/seedu/teachbook/model/classobject/exceptions/NoClassAtIndexException.java
  src/main/java/seedu/teachbook/model/classobject/exceptions/NoClassWithNameException.java
  src/main/java/seedu/teachbook/model/util/SampleDataUtil.java
  src/main/java/seedu/teachbook/storage/JsonTeachBookStorage.java
  src/test/java/seedu/teachbook/logic/commands/CommandTestUtil.java
  src/test/java/seedu/teachbook/logic/commands/EditCommandTest.java
  src/test/java/seedu/teachbook/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/teachbook/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/teachbook/logic/parser/TeachBookParserTest.java
  src/test/java/seedu/teachbook/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/teachbook/testutil/StudentBuilder.java
  src/test/java/seedu/teachbook/testutil/StudentUtil.java
  src/test/java/seedu/teachbook/testutil/TeachBookBuilder.java
  src/test/java/seedu/teachbook/testutil/TestUtil.java
  src/test/java/seedu/teachbook/testutil/TypicalStudents.java
Labels: priority.Medium, type.Chore

#281 Make TeachBook#getGradingSystem return an unmodifiable grading system
  src/main/java/seedu/teachbook/model/ReadOnlyTeachBook.java
  src/main/java/seedu/teachbook/model/TeachBook.java
Labels: type.Enhancement, priority.Medium

#282 Add Javadoc and improve code quality
  src/main/java/seedu/teachbook/commons/core/Config.java
  src/main/java/seedu/teachbook/commons/core/LogsCenter.java
  src/main/java/seedu/teachbook/commons/core/Version.java
  src/main/java/seedu/teachbook/commons/util/AppUtil.java
  src/main/java/seedu/teachbook/commons/util/CollectionUtil.java
  src/main/java/seedu/teachbook/commons/util/ExcelUtil.java
  src/main/java/seedu/teachbook/commons/util/FileUtil.java
  src/main/java/seedu/teachbook/commons/util/JsonUtil.java
  src/main/java/seedu/teachbook/commons/util/StringUtil.java
  src/main/java/seedu/teachbook/logic/parser/CliSyntax.java
  src/main/java/seedu/teachbook/model/classobject/exceptions/DuplicateClassException.java
  src/main/java/seedu/teachbook/model/student/exceptions/DuplicateStudentException.java
  src/main/java/seedu/teachbook/ui/ClassCard.java
  src/main/java/seedu/teachbook/ui/HelpWindow.java
  src/main/java/seedu/teachbook/ui/StudentCard.java
  src/test/java/seedu/teachbook/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/teachbook/logic/commands/EditCommandTest.java
  src/test/java/seedu/teachbook/logic/commands/ListCommandTest.java
  src/test/java/seedu/teachbook/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/teachbook/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/teachbook/logic/parser/ParserUtilTest.java
  src/test/java/seedu/teachbook/logic/parser/TeachBookParserTest.java
  src/test/java/seedu/teachbook/testutil/TypicalIndices.java
Labels: priority.Medium, type.Chore

#283 DG: Update NFR
  docs/DeveloperGuide.md
Labels: type.Documentation

#284 DG: Add use cases for delete and remark
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Medium

#285 DG: Add testing instructions for remark, delete, select
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Medium

#278 Add Javadoc
  src/main/java/seedu/teachbook/model/TeachBook.java
  src/main/java/seedu/teachbook/ui/ClassListPanel.java
  src/main/java/seedu/teachbook/ui/MainWindow.java
  src/main/java/seedu/teachbook/ui/ResultDisplay.java
  src/main/java/seedu/teachbook/ui/UiManager.java
Labels: type.Documentation, priority.Low

#287 Add Javadoc for Model.java and Logic.java
  src/main/java/seedu/teachbook/logic/Logic.java
  src/main/java/seedu/teachbook/model/Model.java
Labels: type.Documentation, priority.Low

#286 Update Test Cases
  build.gradle
  src/main/java/seedu/teachbook/logic/commands/AddCommand.java
  src/main/java/seedu/teachbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/ParserUtil.java
  src/main/java/seedu/teachbook/model/student/Address.java
  src/main/java/seedu/teachbook/model/student/Attendance.java
  src/main/java/seedu/teachbook/model/student/Email.java
  src/main/java/seedu/teachbook/model/student/Name.java
  src/main/java/seedu/teachbook/model/student/Phone.java
  src/main/java/seedu/teachbook/model/student/Student.java
  src/main/java/seedu/teachbook/model/util/SampleDataUtil.java
  src/test/java/seedu/teachbook/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/teachbook/logic/commands/FindCommandTest.java
  src/test/java/seedu/teachbook/logic/parser/TeachBookParserTest.java
  src/test/java/seedu/teachbook/testutil/StudentBuilder.java
  src/test/java/seedu/teachbook/testutil/StudentUtil.java
Labels: type.Chore

#288 Update DG and description in ListCommand
  docs/DeveloperGuide.md
  src/main/java/seedu/teachbook/logic/commands/ListCommand.java
Labels: type.Documentation, priority.Low

#289 Trial user guide shift position
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#294 Add manual test case for add, addClass and find command
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Low

#295 Add use cases for add, delete and edit
  docs/DeveloperGuide.md
Labels: priority.Low

#296 Test to see if code coverage increase with my current test case
  build.gradle
  src/test/java/seedu/teachbook/ui/ClassCardTest.java
Labels: priority.Medium

#299 Update wilfred ppp
  docs/team/wilfredwongkc.md
Labels: priority.Low

#300 Add page break for ppp
  docs/team/wilfredwongkc.md
Labels: priority.Low

#304 Branch update
  build.gradle
  config/checkstyle/suppressions.xml
  src/main/java/seedu/teachbook/logic/parser/AddCommandParser.java
  src/main/java/seedu/teachbook/model/classobject/Class.java
  src/main/java/seedu/teachbook/model/classobject/UniqueClassList.java
  src/main/java/seedu/teachbook/model/student/Student.java
  src/main/java/seedu/teachbook/model/student/UniqueStudentList.java
  src/test/java/seedu/teachbook/logic/commands/AddCommandTest.java
  src/test/java/seedu/teachbook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/teachbook/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/teachbook/logic/parser/TeachBookParserTest.java
  src/test/java/seedu/teachbook/model/student/StudentTest.java
  src/test/java/seedu/teachbook/testutil/ClassBuilder.java
  src/test/java/seedu/teachbook/testutil/StudentBuilder.java
  src/test/java/seedu/teachbook/testutil/TeachBookBuilder.java
Labels: type.Bug, type.Enhancement, priority.High

#305 Branch update
  build.gradle
  src/main/java/seedu/teachbook/model/student/Student.java
  src/test/java/seedu/teachbook/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/teachbook/logic/parser/TeachBookParserTest.java
  src/test/java/seedu/teachbook/testutil/StudentBuilder.java
Labels: type.Enhancement, priority.High

#306 DG: Add use cases for add and edit class
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#307 Issues fix for UG
  docs/UserGuide.md
Labels: type.Documentation

#310 Fix DG use case numbering issues and added more extensions
  docs/DeveloperGuide.md
Labels: priority.Low

#308 UG changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/img.png
Labels: type.Documentation

#313 Update About Us, PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/index.md
  docs/team/fans2619.md
Labels: type.Documentation, type.Enhancement

#314 Remove unused code
  build.gradle
  config/checkstyle/suppressions.xml
  src/main/java/seedu/teachbook/logic/commands/DeleteCommand.java
  src/main/java/seedu/teachbook/logic/commands/GradeCommand.java
  src/main/java/seedu/teachbook/logic/commands/MarkCommand.java
  src/main/java/seedu/teachbook/logic/commands/UnmarkCommand.java
  src/main/java/seedu/teachbook/model/tag/Tag.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/teachbook/logic/commands/AddCommandTest.java
  src/test/java/seedu/teachbook/model/TeachBookTest.java
  src/test/java/seedu/teachbook/model/student/UniqueStudentListTest.java
  src/test/java/seedu/teachbook/testutil/StudentBuilder.java
  src/test/java/seedu/teachbook/testutil/TypicalStudents.java
Labels: priority.Medium, type.Chore

#316 Remove unused testcases that do not work
  build.gradle
  src/main/java/seedu/teachbook/model/TeachBook.java
  src/test/java/seedu/teachbook/logic/LogicManagerTest.java
  src/test/java/seedu/teachbook/model/ModelManagerTest.java
  src/test/java/seedu/teachbook/ui/ClassListPanelTest.java
  src/test/java/seedu/teachbook/ui/CommandBoxTest.java
  src/test/java/seedu/teachbook/ui/HelpWindowTest.java
  src/test/java/seedu/teachbook/ui/MainWindowTest.java
  src/test/java/seedu/teachbook/ui/ResultDisplayTest.java
  src/test/java/seedu/teachbook/ui/StatusBarFooterTest.java
  src/test/java/seedu/teachbook/ui/StudentCardTest.java
  src/test/java/seedu/teachbook/ui/StudentListPanelTest.java
  src/test/java/seedu/teachbook/ui/UiManagerTest.java
Labels: priority.Low

#317 Fix use case extensions for add and edit commands
  docs/DeveloperGuide.md
Labels: priority.Low

#318 Shift "what is TeachBook?" paragraph above
  docs/UserGuide.md
Labels: type.Documentation, priority.Low

#315 Refine UG
  docs/UserGuide.md
Labels: type.Documentation, type.Enhancement

#320 Remove unnecessarily detailed extensions for add and edit
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Low

#323 Update DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddClassSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiAndModel.puml
  docs/images/AddClassSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Documentation, priority.Low
