Repository AY2122S1-CS2103T-W10-2/tp, pull requests merged in 2021-10, with the labels that each got.

#80 Update AboutUs and personal portfolio
  docs/AboutUs.md
  docs/team/fans2619.md
Labels: type.Documentation, priority.Low

#83 Enhance existing features
  src/main/java/seedu/teachbook/commons/core/Messages.java
  src/main/java/seedu/teachbook/commons/core/index/GeneralIndex.java
  src/main/java/seedu/teachbook/logic/commands/AddClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/AddCommand.java
  src/main/java/seedu/teachbook/logic/commands/ClearCommand.java
  src/main/java/seedu/teachbook/logic/commands/SelectClassCommand.java
  src/main/java/seedu/teachbook/model/Model.java
  src/main/java/seedu/teachbook/model/ModelManager.java
  src/main/java/seedu/teachbook/model/TeachBook.java
  src/main/java/seedu/teachbook/model/classobject/UniqueClassList.java
  src/main/java/seedu/teachbook/model/classobject/exceptions/ClassNameWithNameException.java
  src/main/java/seedu/teachbook/model/classobject/exceptions/NoClassAtIndexException.java
  src/main/java/seedu/teachbook/ui/HelpWindow.java
  src/test/java/seedu/teachbook/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.High

#85 Change ModelManager.java
  src/main/java/seedu/teachbook/commons/core/index/DefaultIndices.java
  src/main/java/seedu/teachbook/model/ModelManager.java
Labels: type.Enhancement, priority.High

#89 Implement deleteClass command
  src/main/java/seedu/teachbook/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/teachbook/logic/parser/AddressBookParser.java
  src/main/java/seedu/teachbook/logic/parser/DeleteClassCommandParser.java
  src/main/java/seedu/teachbook/model/Model.java
  src/main/java/seedu/teachbook/model/ModelManager.java
  src/main/java/seedu/teachbook/model/TeachBook.java
  src/test/java/seedu/teachbook/logic/commands/AddCommandTest.java
Labels: type.Story, priority.High

#95 V1.2 enhancement
  config/checkstyle/suppressions.xml
  src/main/java/seedu/teachbook/commons/core/Messages.java
  src/main/java/seedu/teachbook/logic/commands/AddClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/AddCommand.java
  src/main/java/seedu/teachbook/logic/commands/ClearCommand.java
  src/main/java/seedu/teachbook/logic/commands/CommandResult.java
  src/main/java/seedu/teachbook/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/teachbook/logic/commands/DeleteCommand.java
  src/main/java/seedu/teachbook/logic/commands/EditCommand.java
  src/main/java/seedu/teachbook/logic/commands/ExitCommand.java
  src/main/java/seedu/teachbook/logic/commands/FindCommand.java
  src/main/java/seedu/teachbook/logic/commands/HelpCommand.java
  src/main/java/seedu/teachbook/logic/commands/ListCommand.java
  src/main/java/seedu/teachbook/logic/commands/SelectClassCommand.java
  src/main/java/seedu/teachbook/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/DeleteClassCommandParser.java
  src/main/java/seedu/teachbook/logic/parser/ParserUtil.java
  src/main/java/seedu/teachbook/logic/parser/SelectClassCommandParser.java
  src/main/java/seedu/teachbook/model/Model.java
  src/main/java/seedu/teachbook/model/ModelManager.java
  src/main/java/seedu/teachbook/model/TeachBook.java
  src/main/java/seedu/teachbook/model/classobject/Class.java
  src/main/java/seedu/teachbook/model/classobject/ClassName.java
  src/main/java/seedu/teachbook/model/classobject/ClassNameContainsKeywordsPredicate.java
  src/main/java/seedu/teachbook/model/classobject/ClassNameDescriptor.java
  src/main/java/seedu/teachbook/model/classobject/UniqueClassList.java
  src/main/java/seedu/teachbook/storage/JsonAdaptedClass.java
  src/main/java/seedu/teachbook/ui/ClassCard.java
  src/main/java/seedu/teachbook/ui/ClassListPanel.java
  src/main/java/seedu/teachbook/ui/MainWindow.java
  src/test/java/seedu/teachbook/logic/commands/AddCommandTest.java
  src/test/java/seedu/teachbook/logic/commands/CommandResultTest.java
  src/test/java/seedu/teachbook/logic/commands/ExitCommandTest.java
  src/test/java/seedu/teachbook/logic/commands/HelpCommandTest.java
Labels: type.Enhancement
